# .readthedocs.yml

version: 2

build:
  image: latest

python:
  version: 3.6
  install:
    - method: pip
      path: .
    - requirements: requirements.txt

formats:
    - pdf
    - epub
    - htmlzip

